// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIynWgbr5FK95icuQq-15oVc6BflqJ69o',
    appId: '1:1078803179031:web:efd1d8531e00323b9e5e52',
    messagingSenderId: '1078803179031',
    projectId: 'tugasakhir-74ca1',
    authDomain: 'tugasakhir-74ca1.firebaseapp.com',
    storageBucket: 'tugasakhir-74ca1.firebasestorage.app',
    measurementId: 'G-CSTR32F5BJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2oWo82JHaW4kWexahK7RI7vBjHOdAuT0',
    appId: '1:1078803179031:android:2ba088e04a2277729e5e52',
    messagingSenderId: '1078803179031',
    projectId: 'tugasakhir-74ca1',
    storageBucket: 'tugasakhir-74ca1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZBgl2Dn6m-EEg1EFyi6bhEd6q4ZRfSY0',
    appId: '1:1078803179031:ios:a11336ff1e0e11dc9e5e52',
    messagingSenderId: '1078803179031',
    projectId: 'tugasakhir-74ca1',
    storageBucket: 'tugasakhir-74ca1.firebasestorage.app',
    iosBundleId: 'com.example.aplikasinotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZBgl2Dn6m-EEg1EFyi6bhEd6q4ZRfSY0',
    appId: '1:1078803179031:ios:a11336ff1e0e11dc9e5e52',
    messagingSenderId: '1078803179031',
    projectId: 'tugasakhir-74ca1',
    storageBucket: 'tugasakhir-74ca1.firebasestorage.app',
    iosBundleId: 'com.example.aplikasinotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIynWgbr5FK95icuQq-15oVc6BflqJ69o',
    appId: '1:1078803179031:web:72505e74913b6fa79e5e52',
    messagingSenderId: '1078803179031',
    projectId: 'tugasakhir-74ca1',
    authDomain: 'tugasakhir-74ca1.firebaseapp.com',
    storageBucket: 'tugasakhir-74ca1.firebasestorage.app',
    measurementId: 'G-66YFGP20D5',
  );
}
